apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-application
spec:
  replicas: 4
  strategy:
    canary:
      canaryService: my-application-canary
      stableService: my-application-stable
      trafficRouting:
        istio:
          virtualService:
            name: my-application-vsvc
            routes:
              - primary
      steps:
      - setWeight: 20
      - pause: { }
      - setWeight: 40
      - pause: { }
      - setWeight: 60
      - pause: { }
      - setWeight: 80
      - pause: { }
