apiVersion: v1
kind: Service
metadata:
  name: sample-app-canary
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-stable
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sample-app
