apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-application-vsvc
spec:
  hosts:
  - my-application.example.com
  gateways:
  - my-application-gateway
  http:
  - match:
    - headers:
        x-canary:
          exact: "true"
    route:
    - destination:
        host: my-application-canary
        port:
          number: 80
      weight: 100
  - route:
    - destination:
        host: my-application-stable
        port:
          number: 80
      weight: 100
